REPORT ZINCL_PROG_01.
PARAMETERS: V1 TYPE I,
            V2 TYPE I.

DATA: ADD TYPE I,
      SUB TYPE I,
      MUL TYPE I,
      DIV TYPE I.

INCLUDE ZADD_INCL.
INCLUDE ZSUB_INCL.
INCLUDE ZMUL_INCL.
INCLUDE ZDIV_INCL.